# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


Story.create(body: <<-HTML, title: 'Pope Creates Tribunal for Bishop Negligence in Child Sexual Abuse Cases', author_id: 1, header_url: 'https://d262ilb51hltx0.cloudfront.net/max/2000/1*No3f1EMoENLyr7A6r_Vupg.jpeg')
<p>The creation of the tribunal now marks a significant step in holding bishops accountable for the abuses of priests under their charge. Francis’s predecessor, Benedict, reorganized and streamlined the Vatican’s procedures for dealing with priests accused of abuse, but action was slow to come. The move by Francis becomes part of what has been a far more frontal, public and assertive stance in addressing an unseemly legacy for the church.</p>
<p>The church has procedures for judging priests accused of abuse, but until now bishops accused of negligence or cover-ups were almost never held accountable by the church itself.</p>
<p>In announcing the step, the Vatican’s chief spokesman, the Rev. Federico Lombardi, stressed that the tribunal’s responsibilities would include questions of omission. “What one should have done and didn’t do,” he said. “This is another kind of responsibility, and shortcoming, and has to be judged in an appropriate way with appropriate rules.”</p>
<p>Canon law already deals with the question of bishops’ responsibility, he noted. “The issue was whether this was exercised well or poorly. Now we have defined a procedure to determine these cases,” he said.</p>
<p>Father Lombardi said the tribunal would also examine some of the abuse cases perpetrated by clergy that were “still pending” at the Congregation for the Doctrine of Faith. “They are still very numerous and have accumulated,” he said. The tribunal would “accelerate” matters, he said, noting that funds had been set aside to bolster the new section, including hiring new staff.</p>
<p>Currently, the Congregation for the Doctrine of Faith deals with questions of abuse. The new tribunal, and new funding, will bolster its resources to address those cases. “It’s a way to organize work, make it more efficient, and faster,” Father Lombardi said.</p>
<p>The pope will pick a secretary for the tribunal to assist the prefect of the congregation, who will be involved in setting up and organizing the new tribunal.</p>
<p>Cardinal Sean P. O’Malley, who serves on the pope’s Council of Cardinals, a group that advises the pope on a broad range of issues, outlined the proposals on Monday, the first day the council met. The measures were approved unanimously on Tuesday. “The proposals were put in the table, the council approved them, and the pope said, ‘Let’s go forward in this direction,’ ” Father Lombardi said.</p>
<p>The proposals now being put into action set out the procedures for examining complaints of abuse of office by bishops. The complaints will be first investigated by the congregations that the bishops belong to, and then will be judged by the Congregation for the Doctrine of the Faith.</p>
<p>A special new judicial section will be created within the Congregation for the Doctrine of the Faith “to judge bishops with regard to crimes of the abuse of office when connected to the abuse of minors,” a Vatican statement said.</p>
<p>The procedures were proposed by a commission that Francis appointed early in his papacy to examine “best practices” for dealing with sexual abuse and suggest reforms. The group, called the Pontifical Commission for the Protection of Minors, includes victims of abuse by priests.</p>
HTML

User.create(username: 'Loren', password: 'lauren')
User.create(username: 'Lorenzo', password: 'lauren')
Tagging.create(story_id: 1, tag_id: 1)
Tagging.create(story_id: 1, tag_id: 2)
Tagging.create(story_id: 2, tag_id: 2)
Tagging.create(story_id: 3, tag_id: 1)
Follow.create(follower_id: 1, followable_id: 1, followable_type: 'Tag')
Follow.create(follower_id: 1, followable_id: 2, followable_type: 'User')
Follow.create(follower_id: 2, followable_id: 1, followable_type: 'User')
Follow.create(follower_id: 2, followable_id: 3, followable_type: 'Tag')
Follow.create(follower_id: 1, followable_id: 2, followable_type: 'Tag')

Tag.create(name: 'tubular')
Tag.create(name: 'fun!')
Tag.create(name: 'hot!')
Tag.create(name: 'smooth!')
Tag.create(name: "now that's what i call music!")
Tag.create(name: 'chicken wings!')
Tag.create(name: 'fire sale!')
Tag.create(name: 'jericho')


Story.create(body: <<-HTML, title: 'Sunlight on Summer Solstice Will Light Up Fulton Center Hub', author_id: 2, header_url: 'http://static01.nyt.com/images/2015/06/18/nyregion/BLOCKSweb1/BLOCKSweb1-superJumbo.jpg', home_url: 'http://static01.nyt.com/images/2015/06/18/nyregion/BLOCKSweb1/BLOCKSweb1-superJumbo.jpg')
<p>Druids, take note.</p>
<p>On the summer solstice, clouds permitting, the Fulton Center in Lower Manhattan will be filled with more sunshine than has ever before reached its interior.</p>
<p>Rays of sunlight will burnish Sky Reflector-Net — the 79-foot-high convex tracery of aluminum panels and stainless steel cables in the Fulton Center atrium — for more than nine hours on Sunday, between 7:50 a.m. and 5 p.m. (At the winter solstice, by contrast, direct sunlight hits the net for only 70 minutes.)</p>
<p>From 12:15 p.m. until 3:30 p.m., the rays will penetrate about 40 feet below sidewalk level to recesses on the lowest level of the center.</p>
<p>The $1.4 billion Fulton Center, New York’s newest transportation hub, was opened in November by the Metropolitan Transportation Authority, 11 years after the project began, at almost twice the originally estimated budget. It was designed to untangle the tortuous connections among the 2, 3, 4, 5, A, C, J, R and Z subway lines.</p>
<p>This is its first summer solstice.</p>
HTML

Story.create(body: <<-HTML, title: 'Greece and Europe: The Endgame', author_id: 2, header_url: 'http://www.newyorker.com/wp-content/uploads/2015/06/Cassidy-Alexis-Tsipras1-1200.jpg', home_url: 'http://www.newyorker.com/wp-content/uploads/2015/06/Cassidy-Alexis-Tsipras1-1200.jpg')
<p>On Tuesday, Greek Prime Minister Alexis Tsipras addressed Greece’s parliament about stalled talks with the European Union to extend the country’s financial bailout. “I would say the real negotiations are starting now,” he said. What, then, has been going on for the past four and half months, since Tsipras’s Syriza government was elected on a platform of ending the austerity policies that were imposed as part of the original bailout, in 2010, and a revised version, in 2012?</p>
<p>Good question.</p>
<p>One version of events, popular among market commentators and Syriza’s political opponents inside Greece, is that Tsipras and his finance minister, Yanis Varoufakis, have been blundering around without a coherent strategy. In February, they hailed as a negotiating victory an interim agreement that didn’t give the country any money at all, and left it effectively beholden to the European Central Bank, which has been propping up Greece’s banks. Since then, Greek officials have been lashing out at the “troika” of creditors—the E.U., the E.C.B., and the International Monetary Fund—and trying to cobble together enough cash to meet their debt payments. Now, with a payment to the I.M.F. due at the end of the month, they have run out of money and time, leaving them up the creek.</p>
<p>An alternative reading is that the Greek government is playing a dangerous but clever game of chicken. Tsipras and Varoufakis realized early on that their only bargaining leverage was the threat that Greece would default on its debts, crash out of the euro zone, and spark a Europe-wide financial crisis. But the rest of Europe wouldn’t take this threat seriously until Greece was on the brink of defaulting. Only then would the government in Athens be able to wrest any serious concessions from its creditors, such as an agreement to back off on demands for a cut in pensions and a commitment to write down some of Greece’s vast debts. Proponents of this story sometimes mention the fact that Varoufakis, a former academic, is an expert on game theory. (A textbook that he co-wrote has an entire chapter on bargaining games.)</p>
<p>As a distant observer, I don’t claim to know what’s really happening inside the Greek government. But even if it is attempting brinksmanship, there’s no guarantee that it will work. So far, the financial markets have reacted to the possibility of a Greek default with remarkable calm. If traders in bonds issued by Spain, Portugal, and other European countries did start to panic, the E.C.B., which has already started a bond-buying program, could, in theory, step in to stabilize things. “The latest Greek negotiating strategy is to demand a ransom to desist threatening suicide,” Anatole Kaletsky, a British economic commentator, wrote a few days ago. “Such blackmail might work for a suicide bomber. But Greece is just holding a gun to its own head—and Europe does not need to care very much if it pulls the trigger.”</p>
<p>Of course, that analysis may turn out to be incorrect. Letting Greece abandon the euro would demonstrate that entry to the currency zone isn’t irreversible, and this, in turn, could cause problems in other member countries, such as Spain and Portugal. If the markets seem blasé about the prospect of a Grexit, Angela Merkel, the German chancellor, doesn’t appear to share their equanimity; she has stood firm in her support of a deal. And if there is one thing we can be pretty sure of, it is that nothing will happen without Mutti’s approval.</p>
<p>Tsipras, for his part, can hardly turn around and accept the creditors’ current hard-line offer. After repeatedly saying that he won’t concede to blackmail, that would probably be the end of him. Before he could sign on to a deal and sell it to his party, he would need to extract at least one or two more concessions.</p>
<p>Will he get them? I hope so—not out of any particular sympathy for Tsipras and Varoufakis, who have managed to alienate many of their potential allies in countries such as Italy and France, but because the Greek population has already made enormous sacrifices to stay in the euro zone, and it deserves a break. Between 2009 and 2014, under the guidance of the troika, Greece was subjected to a huge fiscal shock, which led to a local version of the Great Depression. G.D.P. fell by about a quarter. The unemployment rate rose to twenty-eight per cent. After all this pain was endured, the public finances have improved quite a bit. Until recently, when uncertainty about the bailout extension caused another economic downturn, Greece was expected to run a primary surplus this year. (That means it would have covered the costs of all its expenditures except interest payments on its debts.) The country’s overall indebtedness has continued to grow, but largely as a consequence of the bailouts, which piled debt upon debt.</p>
<p>In short, Greece has already done much of what its creditors demanded. Karl Whelan, an economist at University College Dublin, points out as much in an informative new post on Medium. Some critics, he writes, say, “The Greek people have no stomach for hard decisions. One has to wonder whether people who think this are conscious of even the basic facts about the scale of fiscal adjustment experienced in Greece.” Such has been the turnaround in Greece’s finances that negotiators for the two sides have been able to agree on a set of fiscal targets for the next few years, with the sum still under dispute being reduced to about two billion euros a year. Even for a small country like Greece, that’s not a huge amount.</p>
<p>The real sticking point isn’t the budget targets: it’s that Greece’s creditors want further cuts in its pension system and an extension of its value-added tax on goods and services. Looked at strictly in budgetary terms, these demands are both defensible. Until recently, Greece’s pension system was grossly underfunded and its tax system was a shambles. Given these and other shortcomings in the country’s economic institutions, many people now argue that it should never have been allowed to join the euro zone in the first place.</p>
<p>But Greece was allowed in, and the question now is whether both sides should show a bit more flexibility. As I’ve said before, I’m not entirely convinced that leaving the euro zone would be an economic tragedy for Greece. With a new currency, a big devaluation against the euro, and a write-off of many of its debts, it could conceivably do better for itself. But polls show the majority of Greeks, for whatever reason, still want to be members of the euro club.</p>
<p>Perhaps I’m a hopeless optimist, but my hunch is that they will get their wish. On paper, the outlines of a deal aren’t hard to draw up. Greece agrees to meet its creditors halfway on pensions and the value-added tax, with some of the numbers being fudged. The creditors give a bit more ground on the overall budget targets, and they also agree to start a process that could lead to long-term debt relief, which Greece badly needs. Both sides declare victory, and the crisis abates—at least for now.</p>
<p>At this stage, the barriers to an agreement are as much political as economic. Will Tsipras agree to edge across one of his “red lines” and agree to pension and wage cuts? And will the European establishment, rather than taking the risk of encouraging radicals in Spain, Portugal, and other countries, decide to cut Greece adrift? In the next few days, we should find out the answers.</p>
HTML
